### ISSUE TITLE
Sort the list of currencies in the currency chooser

### ISSUE THREAD

**Issue by t-8ch** [billthefarmer/specie#1]
It would be nice if the currency selection list would be sorted somehow.
Due to the many currencies that are supported by the app (thanks!) it is a bit hard to find a new one in the list.
Sorting the list by some discoverable order would help a lot.

I would propose to sort alphabetically by currency code.

If this is acceptable  I can submit a PR.

**Comment by billthefarmer** [comment]
That's easier said than done. The app is built around fixed lists of currency codes, names, etc, embedded in the code probably derived from the data file from Floatrates. The selection dialog just returns a list of indexes. You would either have to sort the fixed lists or sort the lists used in the dialog, ensuring that the correct indexes are returned. Or return currency codes and change the logic.

A possible easier option could be to search on the currency code...

![Screenshot_20221006-123148 1](https://user-images.githubusercontent.com/3448386/194302121-8b65a46a-267d-45f5-baec-4fcc3e44ca5f.png)

**Comment by t-8ch** [comment]
Yes, searching would also work, it may even be nicer.
I already prepared a PR for the sorting at #2. But I think even if the sorting is not needed the restructuring of the lists that is done in this PR would make sense to be kept.

Off-topic question:

Aren't "Currency" and "Specie" essentially the same app just with different sets of currencies and a different update logic?
Would it not make sense to unify them into a single codebase using gradle variants or even a single app with a settings toggle?

**Comment by billthefarmer** [comment]
That's correct, I started attempting to build one app with both sets of data, but it rapidly got far too messy, so I decided to copy the relevant bits and build another app. My apps are generally intended to do one thing reasonably well.

**Comment by billthefarmer** [comment]
OK, I have added interactive search, that will be in the next version.

**Comment by t-8ch** [comment]
Thanks!
Also in general many thanks for your great app(s).

(PS: the release/tag for 1.07 is missing)

**Comment by billthefarmer** [comment]
I left the release until today because I wanted to see if I could make the search icon move to the right, but it didn't work.
