### ISSUE TITLE
Can you create the same app for cryptocurrencies? I really need it

### ISSUE THREAD

**Issue by Wjxfi** [billthefarmer/specie#4]

**Comment by billthefarmer** [comment]
The last time I looked there wasn't a free source of data. I've got too many apps already.

**Comment by Wjxfi** [comment]
https://www.f-droid.org/packages/de.cloneapps.crypto_prices/

this huge application (50+ mb) uses coingecko

coingecko is not open source, but it is better than the rest. It's also used by unstoppable wallet
