### ISSUE TITLE
[Feature Request] Update to targetSdk 33+

### ISSUE THREAD

**Issue by sebastien46** [billthefarmer/specie#5]
I was wondering if updating the app to targetSdk 33+ was possible while still being able to retain the minSdk 14 value for compatibility with older devices as well as support for new android features.

**Comment by billthefarmer** [comment]
This is possible with this particular app. Do you have a reason? I've looked at the changes and can't see anything significant. The reason why I ask is that increasing the target and compile API increases restrictions and deprecation of useful APIs usually for no particular reason. For example several of my apps would no longer be usable if I increased beyond 28.

**Comment by sebastien46** [comment]
I only wanted the targetSdk bump for one minor feature: [themed/monochrome app icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming).
I can totally understand why you wouldn't want to upgrade for such a poor tradeoff.

**Comment by billthefarmer** [comment]
That only works if the app has a 'monochromatic' icon. None of my apps have.
Edit: I don't think it is dependent on the app API level.
