### ISSUE TITLE
Incorrect UAE flag

### ISSUE THREAD

**Issue by lloyd-dada** [billthefarmer/specie#6]
Many thanks for this open source app.
The flag of the United Arab Emirates with the currency AED is not correct.
I am using the app with F Droid.
![IMG_20230812_150222](https://github.com/billthefarmer/specie/assets/25735673/0092f5dd-9e99-4b76-b1ac-6c0a642e323f)
[https://en.m.wikipedia.org/wiki/Flag_of_the_United_Arab_Emirates](https://en.m.wikipedia.org/wiki/Flag_of_the_United_Arab_Emirates) 

Thank you.

**Comment by billthefarmer** [comment]
OK, thank you.
