### ISSUE TITLE
Some currencies can't be enabled

### ISSUE THREAD

**Issue by jhotadhari** [billthefarmer/specie#7]
Hi,

Some currencies can't be enabled:
- Guatemalan Quetzal
- Honduran Lempira
- Nicaraguan Córdoba

All other currencies I've tested can be added.

Android 10 (crDroid 6.12)

Thank you!!!!

**Comment by jhotadhari** [comment]
Yesterday I tried again to add these currencies to the list and it worked without problems.

Today their exchange rate is displayed `NaN`

I checked the exchange rate at https://www.floatrates.com/currency/gtq/ 
The result is *Can't find any latest rates for GTQ.*

But the api https://www.floatrates.com/daily/gtq.json seems to be alright.

**Comment by billthefarmer** [comment]
The app will not attempt to display currencies that are not in the current downloaded data. It was originally designed around  the currencies that were in the data at the time.

It may be that the data is not available. I don't know.

Edit: I checked the data today (26/9), and none of the above currencies are in it: https://www.floatrates.com/daily/eur.json
