### ISSUE TITLE
ALL, HNL cannot be added to currency list

### ISSUE THREAD

**Issue by wpost** [billthefarmer/specie#9]
Problem: ALL, HNL cannot be added to the currency list

Steps to reproduce:

1. On the main screen, tap + to open the list of available currencies.
2. Find ALL or HNL and long press it. Options will appear; tap on "select". You are returned to the main screen.

Expected behavior: The selected currency has been added to the currency list.
Observed behavior: The addition silently fails. The currency is not added to the currency list, nor is an error message shown.

Additional notes: I discovered the problem with HNL during normal use. Wishing to be helpful, I spot checked a few other currencies with H, N, or L in their names, and found that ALL has the same problem. Other currencies with one of those letters in their names worked as expected however, so I am not sure what the pattern of failure is here.

Environment where observed: OnePlus 8, OEM Android 13 with 2023-08-05 security update.

**Comment by billthefarmer** [comment]
See #7. Please check closed issues before opening a new one.

**Comment by wpost** [comment]
Oof, you're right. Closing as duplicate, and my apologies.
